runtime: python39

handlers:
- url: /static
  static_dir: static

env_variables:
  CLOUD_SQL_USERNAME: admin
  CLOUD_SQL_PASSWORD: admin430
  CLOUD_SQL_DATABASE_NAME: users
  CLOUD_SQL_CONNECTION_NAME: ciphersquad:us-central1:cipher-squad